
#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}-{branch}

# branches to build
branches:
  # blacklist
  except:
    - gh-pages

# Skipping commits affecting specific files (GitHub only). More details here: /docs/appveyor-yml
skip_commits:
  # Default `skip` messages are applied even on tag builds with APPVEYOR_IGNORE_COMMIT_FILTERING_ON_TAG==true
  message: /\[_skip ci_\]|\[_ci skip_\]|\[_skip_ci_\]|\[_ci_skip_\]/
  files:
    - README.md
    - THIRD_PARTY_NOTICES.md
#    - docs/*
#    - '**/*.png'
#    - '**/*.jpg'
#    - '**/*.jpeg'
#    - '**/*.bmp'
#    - '**/*.gif'
#    - '**/*.js'
#    - '**/*.txt'
#    - '**/*.md'

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2022

# environment variables
environment:
  APPVEYOR_IGNORE_COMMIT_FILTERING_ON_TAG: true
  git_user_email: theqwertiest@outlook.com
  git_user_name: TheQwertiest
  GITHUB_TOKEN:
    secure: Mxx+GpxY7koV77u4Mdjn6QWJdoaEgrWpKRGjDQf3DGRHniY7ZN6b3sW1MEpyUG7r6KDyIsrbQzNa8uc1oJIUtMYA/YzuoihOwlkS4RMv34gKruI4JEbN/I3LHSpBFa7v

# this is how to allow failing jobs in the matrix
matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

for:
  -
    matrix:
      only:
        - configuration: Release
    cache:
      - workspaces\packages -> **\packages.config

cache:
  - workspaces\packages -> **\packages.config

# scripts that run after cloning repository
install:
  # GitHub CLI
  - choco install gh -y
  - refreshenv
  - gh config set -h github.com git_protocol https
  # PIP
  - py -3 -m pip install semver
  # Component
  - py -u scripts\setup.py

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
  - Win32
  - x64

# build Configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

# Build settings, not to be confused with "before_build" and "after_build".
# "project" is relative to the original build directory and not influenced by directory changes in "before_build".
build:
  parallel: true                  # enable MSBuild parallel builds
  project: workspaces\foo_discord_rich.sln      # path to Visual Studio solution or project

  # MSBuild verbosity level
  verbosity: normal

# scripts to run before build
before_build:
  - nuget restore workspaces\foo_discord_rich.sln

# to run your custom scripts instead of automatic MSBuild
build_script:

# scripts to run after build (working directory and environment changes are persisted from the previous steps)
after_build:

# scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
before_package:
  - if '%configuration%' == 'Debug' (
      py scripts\pack_component.py --configuration %configuration% --platform %platform% &&
      ren "_result\%platform%_%configuration%\foo_discord_rich.fb2k-component" "foo_discord_rich-%platform%.fb2k-component-debug"
    )
    else (
      py scripts\pack_component.py --configuration %configuration% --platform %platform% &&
      ren "_result\%platform%_%configuration%\foo_discord_rich.fb2k-component" "foo_discord_rich-%platform%.fb2k-component" &&
      ren "_result\%platform%_%configuration%\foo_discord_rich_pdb.zip" "foo_discord_rich_pdb-%platform%.zip"
    )

# to disable automatic builds
#build: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  # pushing a single file with environment variable in path and "Deployment name" specified
  - path: _result\$(platform)_$(configuration)\foo_discord_rich-$(platform).fb2k-component
    name: DRP package ($(configuration), $(platform))
  - path: _result\$(platform)_$(configuration)\foo_discord_rich_pdb-$(platform).zip
    name: DRP PDB package ($(configuration), $(platform))
  - path: _result\$(platform)_$(configuration)\foo_discord_rich-$(platform).fb2k-component-debug
    name: DRP package ($(configuration), $(platform))

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
deploy:
  description: 'Dummy description'
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  artifact: /foo_discord_rich.*/
  prerelease: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only


# scripts to run before deployment
before_deploy:

# scripts to run after deployment
after_deploy:

# to run your custom scripts instead of provider deployments
deploy_script:

# to disable deployment
# deploy: off

#---------------------------------#
#        global handlers          #
#---------------------------------#

# on successful build
on_success:
  # issues clean up
  - ps: |
        If ($env:APPVEYOR_REPO_TAG -eq $true -and $env:CONFIGURATION -eq "Release" -and $env:PLATFORM -eq "x64")
        {
          py -u submodules\fb2k_utils\scripts\close_gh_issues.py
        }
  # gh-pages
  - ps: |
        If ($env:APPVEYOR_REPO_TAG -eq $true -and $env:CONFIGURATION -eq "Release" -and $env:PLATFORM -eq "x64")
        {
          git config --global credential.helper store
          Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GITHUB_TOKEN):x-oauth-basic@github.com`n"
          git config --global user.email $env:git_user_email
          git config --global user.name $env:git_user_name
          git clone -q --depth=1 -b gh-pages https://github.com/$($env:APPVEYOR_REPO_NAME).git gh-pages
          py -u scripts\update_gh_pages.py
          cd gh-pages
          git add -A 2>&1
          git commit -q -m "Updated documentation: $env:APPVEYOR_REPO_TAG_NAME ($env:APPVEYOR_REPO_COMMIT)"
          git push -q origin gh-pages
          cd $env:APPVEYOR_BUILD_FOLDER
        }

# on build failure
on_failure:

# after build failure or success
on_finish:

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
